### PR TITLE
Redesign AdminLessonExerciseCard

### PR DESCRIPTION
**Pull request by flacial**
Related to #1990 

### Description

This PR redesign the `AdminLessonExerciseCard` to achieve:

1. No extra space between the paragraphs when they're short
2. Looks good on mobile
3. Admin can copy Discord username

### Visual difference

<details>
<summary>
Before
</summary>
image
image
</details>

<details>
<summary>
After
</summary>
image
image

</details>

### CODE REVIEW

**Comment by SlyBouhafs** [comment]
Can you add the relevant path for the admin exercises page?

**Comment by SlyBouhafs** [comment]
> We don't have this page yet. It'll be added in a subsequent PR
Oh ok, i wanted to leave a few comments on it via the Vercel comment feature. I left a few comments on this image instead:
adminexercisepage

**Comment by flacial** [comment]
> > We don't have this page yet. It'll be added in a subsequent PR
> 
> Oh ok, i wanted to leave a few comments on it via the Vercel comment feature. I left a few comments on this image instead:

I addressed the comments in the last commit. This is how it now looks:

<details>
<summary>
Image
</summary>
image
</details>

When the admin click the username, it'll open the user's profile page.

**Comment by SlyBouhafs** [comment]
> I addressed the comments in the last commit. This is how it now looks:

Nice, appending an `@` was a good idea! I also think that we should make the unflag and remove exercise buttons a bit a more obvious, should they look like button or links? Should they have the same color? The remove button should probably be in red and the unflag maybe green?

**Comment by flacial** [comment]
> > I addressed the comments in the last commit. This is how it now looks:
> 
> Nice, prepending an `@` was a good idea! I also think that we should make the unflag and remove exercise buttons a bit a more obvious, should they look like button or links? Should they have the same color? The remove button should probably be in red and the unflag maybe green?

I like the idea of changing the remove button color to red, but the unflag is suitable because purple represents a primary action.

**Comment by flacial** [comment]
@SlyBouhafs What do you think?

image

I chose orange because green represents something positive, something good. While orange is like "Are you sure you want to unflag this?".

**Review by SlyBouhafs — APPROVED** [review]

**Comment by SlyBouhafs** [comment]
Looks good to me!

**Pull request merged**
