### PR TITLE
feat: Add text colors

### LINKED ISSUE #1771: design: Add text colors to styles variables
Add the following [styles](https://www.figma.com/file/f9xRyl1bJOjtBRd8zFORzg/c0d3?node-id=727%3A4390) to the styles [variables](https://github.com/garageScript/c0d3-app/blob/master/scss/__variables.module.scss).

image

### PR DESCRIPTION
**Pull request by flacial**
Closes #1771 

This PR will...

- Add `dark purple`, `grey purple`, and `light` (which is basically white) colors to `colors.module.scss`

### CODE REVIEW

**Comment by songz** [comment]
Would it be confusing that variables are defined in a separate file when there's a file for variables? https://github.com/garageScript/c0d3-app/blob/master/scss/__variables.module.scss

**Comment by SlyBouhafs** [comment]
This will be a conflicting PR because this PR #1811 uses the same file to store the font styling for all the different text elements.

We need to agree on a structure and update the PR, here's what i propose:
- Have all colors inside `_colors.module.scss` and style with keywords such as `fg-color` and `bg-color` like in the design doc.
- OR Have `_background.module.css` for background colors and `_text.module.css` for foreground colors and move the font styling to `_typography.module.css`.

What do you guys think? I'd pick the first option, we don't have too many colors and i don't feel like it is necessary to break them into two separate files.

**Comment by flacial** [comment]
> * OR Have `_background.module.css` for background colors and `_text.module.css` for foreground colors and move the font styling to `_typography.module.css`.

I like this option, but the first one is fine as we don't have many colors.

**Comment by SlyBouhafs** [comment]
> > * OR Have `_background.module.css` for background colors and `_text.module.css` for foreground colors and move the font styling to `_typography.module.css`.
> 
> I like this option, but the first one is fine as we don't have many colors.
> 
> Do you suggest to move the colors to `_colors.module.scss` and reset `_text.module.scss` content?

Yeah, i think we should keep all colors in a single `_colors.module.scss` file.
I can move the text styling to `_typography.module.css` too, the name feel more appropriate.

**Review by SlyBouhafs — APPROVED** [review]

**Review by songz — APPROVED** [review]

**Review by SahilKalra98 — APPROVED** [review]

**Pull request merged**
