### PR TITLE
Improve MdInput stories and update snapshots

### LINKED ISSUE #2870: MdInput stories do not allow for user input
The MdInput stories do not allow the user to input text. It would be nice to fix this so that you can interact with the story and see how the MdInput component works.

To see the current behavior, have the dev environment set up on your local machine and run `yarn storybook export NODE_OPTIONS=--openssl-legacy-provider`. Then go to the `Components/MdInput` stories.

The reason why the MdInput does not respond to input is because its `value` and `onChange` props come from the parent component, `ReviewCard`. If you go to the story for `ReviewCard` you will see that the`MdInput` **does** respond to user input.

It could be argued that the `MdInput` stories do not need "fixing", because storybook is supposed to showcase the individual components, not their parent component's logic. If so, feel free to close this issue.

### PR DESCRIPTION
**Pull request by scotthallock**
### Overview
This PR fixes the broken input on the `MdInput` component's stories, and also add new stories.

The `MdInput`'s `value` and `onChange` props are passed from the parent component's state. The parent component is `ReviewCard`, and the `ReviewCard` stories **do** allow for user input in the MdInput component.

### Changes
- Added a [Template](https://storybook.js.org/docs/react/writing-stories/introduction#using-args) to the MdInput.stories.tsx file which has a state hook to mock the parent component state.
- Added a new stories, which better showcase how the component will render markdown input and HTML input.

### Notes
- Snapshots also updated.
- This PR replaces #2868

### Related issues
- Closes #2870

### CODE REVIEW

**Comment by scotthallock** [comment]
This PR also deletes the `_WithSubmissionButtons` story, because Storybook is meant for developing and showcasing components in isolation.

**Review by flacial — APPROVED** [review]
LGTM!

**Review by SlyBouhafs — APPROVED** [review]

**Comment by JasirZaeem** [comment]
@all-contributors please add @scotthallock for code

**Comment by JasirZaeem** [comment]
@all-contributors please add @scotthallock for code

**Pull request merged**
