### PR TITLE
Update Next to 10.2 and enable Webpack 5

### PR DESCRIPTION
**Pull request by ggwadera**
- `next` updated to version 10.2
- `@next/mdx` updated to version 10.2
- Enabled webpack 5
- Modal image test broke so this PR includes a fix

Next.js release notes:

https://nextjs.org/blog/next-10-2
https://nextjs.org/blog/next-10-1

Instructions to enable Webpack 5:

https://nextjs.org/docs/messages/webpack5

### CODE REVIEW

**Review by kondanna — APPROVED** [review]

**Comment by Ulisseus** [comment]
I can't login on vercel. 500 internal server error `column "expires" does not exist`. Was anything db related merged after this PR was created or it's webpack 5 issue?

**Comment by kondanna** [comment]
> I can't login on vercel. 500 internal server error `column "expires" does not exist`. Was anything db related merged after this PR was created or it's webpack 5 issue?

I merged lessonType after this PR was created. It made some DB columns not null.

**Comment by ggwadera** [comment]
> I can't login on vercel. 500 internal server error `column "expires" does not exist`. Was anything db related merged after this PR was created or it's webpack 5 issue?

It's because of the session migration PR, I made this one before merging that.

**Comment by ggwadera** [comment]
I updated the branch, login works now.

**Pull request merged**
