### PR TITLE
 Display challenge description over ReviewCard diffView - Updated

### LINKED ISSUE #1154: Add Challenge Description to ReviewCard
Currently, when I am reviewing code, the first thing I do is open another browser tab to get the description of the challenge.
I propose we add a ChallengeQuestionCard component to ReviewCard. 

Current Review Card:
image

Proposed Review Card:
image

The proposed changes would be:
 - Add ChallengeQuestionCard component to ReviewCard.
 - Remove the current challenge title, as the ChallengeQuestionCard already displays this.

### PR DESCRIPTION
**Pull request by flacial**
Close #1154 

Before:

`null`

After:

image
image

**Demo:** https://c0d3-app-lx5bewy5e-c0d3.vercel.app/

### CODE REVIEW

**Comment by anthonykhoa** [comment]
Will these changes for `ReviewCard` also be present in the storybook?

**Comment by songz** [comment]
> Will these changes for `ReviewCard` also be present in the storybook?

I see the changes in the storybook: https://deploy-preview-1372--youthful-thompson-448332.netlify.app/?path=/story/components-reviewcard--active-card

Although, seems like some queries are missing in the story book.

**Review by songz — APPROVED** [review]

**Comment by flacial** [comment]
@songz I forgot about storybook. I'll check it!

**Review by mino323 — APPROVED** [review]

**Comment by songz** [comment]
I thought it worked well on storybook, the query error seems like a separate issue.

**Comment by songz** [comment]
@all-contributors please add @flacial for code

**Pull request merged**
