### PR TITLE
 close #473 - add mobile layout for challenge page 

### LINKED ISSUE #473: Certain parts of  mobile site look bad
The mobile version of the website has various pages that do not look good on mobile.

* Lesson challenges page
* Curriculum page
* Profile page

### PR DESCRIPTION
**Pull request by Ulisseus**
This PR fixes challenge page for mobile devices. Currently it doesn't look very [good](https://www.c0d3.com/curriculum/5). 

Smaller screens (less than `768px` wide, md bootstrap breakpoint) will see only challenge description while challenge list is hidden. Clicking on`SHOW CHALLENGES` results in modal overlay with challenge list. Clicking on challenge name/background hides it. 

Non-mobile page is pretty much the same except for challenge list background color. Previously it was half transparent, I changed it to fully opaque (I doubt anyone will notice the difference). It was messing with overlay. 

[Vercel](https://c0d3-app-cvjn3p0cr-c0d3.vercel.app/curriculum/5). Enable responsive design mode. Click on `SHOW CHALLENGES`, try selecting various challenges.

### CODE REVIEW

**Review by ggwadera — COMMENTED** [review]
Doing some quick playing around on the preview, already noticed some bugs:

- Modal doesn't close when clicking on a challenge. I need to click again to make it close.
- Reducing the screen size doesn't hide the challenges list. [image](https://user-images.githubusercontent.com/16023489/115448126-b4f2d180-a1ef-11eb-8c9d-cc0fa6eecdec.png)
- Increasing the screen size back, the card width doesn't change and the layout doesn't return to the wide one. [image](https://user-images.githubusercontent.com/16023489/115447587-0f3f6280-a1ef-11eb-82e1-b356b21180a1.png)

You'll probably need to watch the screen width value to fix these, or do some media queries with CSS to set the `display` value. 

It's not really some critical bugs but they affect the user experience when resizing the window, and screens smaller than 768px are still pretty common.

**Review by kondanna — APPROVED** [review]
looks really good

**Comment by Ulisseus** [comment]
>Modal doesn't close when clicking on a challenge. I need to click again to make it close.
It's by design. One click is for selecting challenges, two is for hiding modal. Is it too confusing? It's pretty easy to change it to one click. 

As for resizing I know no easy way to rerender components on resizing. Adding even listeners to window is not the react way because it will trigger too much rerenders. With debounce transitions won't look smooth.

**Comment by ggwadera** [comment]
> It's by design. One click is for selecting challenges, two clicks on the same challenge is for hiding modal. Is it too confusing? It's pretty easy to change it to one click.

It's kinda confusing to me, can't recall if I ever seen a modal work like this.

> As for resizing I know no easy way to rerender components on resizing. Adding event listeners/hooks to window dimensions is not the react way because it will trigger too much rerenders.

You're right, the React way is using a [hook](https://usehooks.com/useWindowSize/) haha. I don't know if the performance cost is too high, would need to test it out.

**Comment by Ulisseus** [comment]
I removed double tap. Updated [Vercel](https://c0d3-app-cvjn3p0cr-c0d3.vercel.app/curriculum/5).

**Review by songz — APPROVED** [review]

**Pull request merged**
