### PR TITLE
[#1203] fix broken tests

### LINKED ISSUE #1203: Upstream tests are broken broken - All merges on hold
Current HEAD on master branch is breaking tests.

Will pass is I comment out [test for no name in context](https://github.com/garageScript/c0d3-app/blob/master/components/ChallengeMaterial.test.js#L382) and [test for adding comments](https://github.com/garageScript/c0d3-app/blob/master/components/ChallengeMaterial.test.js#L358).

Also has to update `can-i-use`, which would fail unless we remove `package-lock.json`. To find the update prompt, run one test: `yarn testdev components/ChallengeMaterial.test.js`

### PR DESCRIPTION
**Pull request by coltonehrman**
Honestly, not sure why or how these tests were working to begin with. I believe they are still going to be flaky and will run into this same issue again.

I updated snapshots and made sure to keep `mock data` "pure" by creating copies of it in every test so no test is overwriting the data for another.

In my opinion, the amount of snapshot tests is way too much, and should be removed in favor of behavior testing and leave the snapshots test to the story components.

### FIX _(I believe anyways, hard to tell with the amount of flakiness and issues going on)_
See - https://github.com/garageScript/c0d3-app/pull/1204/commits/1b4220ef16fad1cc03156c655196d502c1f940c9

`Should be able to add comments` test case was not awaiting a result from the rendered component

See - https://github.com/garageScript/c0d3-app/pull/1204/commits/8c0e3a2b73b21592ffc9e1aaf0376cf0c0ea8003

*Removed the broken part of the test as the initial replace from https://github.com/garageScript/c0d3-app/pull/1204/commits/1b4220ef16fad1cc03156c655196d502c1f940c9 was actually not doing anything, added TODO to replace with a valid test*

Closes #1203

### CODE REVIEW

**Comment by coltonehrman** [comment]
> Honestly, not sure why or how these tests were working to begin with. I believe they are still going to be flaky and will run into this same issue again.
> 
> I updated snapshots and made sure to keep `mock data` "pure" by creating copies of it in every test so no test is overwriting the data for another.
> 
> In my opinion, the amount of snapshot tests is way too much, and should be removed in favor of behavior testing and leave the snapshots test to the story components.
> 
> Closes #1203

First build FAILED - See https://github.com/garageScript/c0d3-app/runs/4572676433?check_suite_focus=true

Testing skipping of `ChallengeMaterial.test` test to see if the fixes it

**Comment by coltonehrman** [comment]
> > Honestly, not sure why or how these tests were working to begin with. I believe they are still going to be flaky and will run into this same issue again.
> > I updated snapshots and made sure to keep `mock data` "pure" by creating copies of it in every test so no test is overwriting the data for another.
> > In my opinion, the amount of snapshot tests is way too much, and should be removed in favor of behavior testing and leave the snapshots test to the story components.
> > Closes #1203
> 
> First build FAILED - See https://github.com/garageScript/c0d3-app/runs/4572676433?check_suite_focus=true
> 
> Experiment skipping of `ChallengeMaterial.test` test to see if the fixes it

Skipping of `ChallengeMaterial.test` shows that it is the test suite causing the issues - See https://github.com/garageScript/c0d3-app/runs/4572696858?check_suite_focus=true

*Build still failing because code coverage is now below 100%*

**Review by songz — APPROVED** [review]

**Review by tomrule007 — APPROVED** [review]

**Comment by songz** [comment]
Note: don't look at the build output beacuse it doesn't give you full error. Gotta run it locally to see error.

**Comment by tomrule007** [comment]
I created an issue to further dive into this issue #1205

**Pull request merged**
